server:
  host: 127.0.0.1
  port: 8080

mysql:
  host: 127.0.0.1
  port: 9090
  username: root
  password: 1234567890
  dbname: cloud
  otherConfig: charset=utf8mb4&parseTime=True&loc:Local

redis:
  addr: 127.0.0.1:6379
  index: 0
  protocol: 3

jwt:
  secret: go-cloud
  expired: 24
